# Generated by Django 4.1.2 on 2022-10-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
